#!/usr/bin/env bash

declare -a options=(
"Logout"
"Lock screen"
"Reboot"
"Shutdown"
"Suspend"
"Quit"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -i -p 'Shutdown menu:')

case $choice in
    'Logout')
        answer="$(echo -e "No\nYes" | dmenu -i -p "Logout?")"

        if [[ $answer == "Yes" ]]; then
            killall xmonad || echo "Process was not running."
        fi

        if [[ $answer == "No" ]]; then
            echo "User chose not to logout." && exit 1
        fi
        ;;
    'Lock screen')
        echo "TODO"
        ;;
    'Reboot')
        answer="$(echo -e "No\nYes" | dmenu -i -p "Reboot?")"

        if [[ $answer == "Yes" ]]; then
            systemctl reboot
        fi

        if [[ $answer == "No" ]]; then
            echo "User chose not to reboot." && exit 0
        fi
        ;;
    'Shutdown')
        answer="$(echo -e "No\nYes" | dmenu -i -p "Shutdown?")"

        if [[ $answer == "Yes" ]]; then
            systemctl poweroff
        fi

        if [[ $answer == "No" ]]; then
            echo "User chose not to shutdown." && exit 0
        fi
        ;;
    'Suspend')
        answer="$(echo -e "No\nYes" | dmenu -i -p "Suspend?")"

        if [[ $answer == "Yes" ]]; then
            systemctl suspend
        fi

        if [[ $answer == "No" ]]; then
            echo "User chose not to suspend." && exit 0
        fi
        ;;
	'Quit')
		echo "Program terminated." && exit 0
	;;
	*)
		exit 0
	;;
esac
