#!/bin/bash

sta

# TODO auto detect screens and change using xrand
# Example: If we find a screen connected via Display-Port
# xrandr | grep 'DP-1 connected' | ifne xrandr --output DP-1 --auto --left-of LVDS-1-1

# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

stalonetray &
xscreensaver -no-splash &
blueman-manager &
wpa_gui &
clipmenud &
Enpass &
/usr/bin/xset r rate 265 40

# Remap caps lock to left control. This is not strictly speaking
# xmonad related, but it's handy if you're a vim user.
setxkbmap -option 'ctrl:nocaps'

# Change the default X cursor away from the "X"
xsetroot -cursor_name left_ptr

# Now, finally, start xmonad
exec xmonad
